### ISSUE TITLE
App chrashes when there isn't any internets available

### ISSUE THREAD

**Issue by NathanBastiaans** [CompraBV/compra-app#2]
App shows the "loading domains" toast and then just straight up crashes when there are no interwebs.

**Comment by NathanBastiaans** [comment]
![](http://you.co.za/wp-content/uploads/2014/08/cat-sad.jpg)

This is an example image that can't be reached without the interwebz

**Comment by bobdesaunois** [comment]
![awshit](https://cloud.githubusercontent.com/assets/6050628/9317458/01e388e8-453c-11e5-8a78-57b551a22643.jpg)

**Comment by NathanBastiaans** [comment]
lol this was fixed way back in the dayz
